-- liquibase formatted sql

-- changeset ilyatr:1-insert-users
INSERT INTO users (name, email, password) VALUES
('Ivan', 'ivan123@example.com', 'pass123'),
('Anna', 'anna456@example.com', 'pass456'),
('Sergey', 'sergey789@example.com', 'pass789'),
('Maria', 'maria101@example.com', 'pass101'),
('Dmitry', 'dmitry102@example.com', 'pass102'),
('Elena', 'elena103@example.com', 'pass103'),
('Pavel', 'pavel104@example.com', 'pass104'),
('Olga', 'olga105@example.com', 'pass105'),
('Nikolay', 'nikolay106@example.com', 'pass106'),
('Tatiana', 'tatiana107@example.com', 'pass107'),
('Alexey', 'alexey108@example.com', 'pass108'),
('Yulia', 'yulia109@example.com', 'pass109'),
('Andrey', 'andrey110@example.com', 'pass110'),
('Irina', 'irina111@example.com', 'pass111'),
('Vladimir', 'vladimir112@example.com', 'pass112'),
('Natalia', 'natalia113@example.com', 'pass113'),
('Mikhail', 'mikhail114@example.com', 'pass114'),
('Svetlana', 'svetlana115@example.com', 'pass115'),
('Roman', 'roman116@example.com', 'pass116'),
('Karina', 'karina117@example.com', 'pass117'),
('Grigory', 'grigory118@example.com', 'pass118'),
('Larisa', 'larisa119@example.com', 'pass119'),
('Timur', 'timur120@example.com', 'pass120'),
('Alena', 'alena121@example.com', 'pass121'),
('Vadim', 'vadim122@example.com', 'pass122'),
('Daria', 'daria123@example.com', 'pass123'),
('Artem', 'artem124@example.com', 'pass124'),
('Evgenia', 'evgenia125@example.com', 'pass125'),
('Igor', 'igor126@example.com', 'pass126'),
('Ksenia', 'ksenia127@example.com', 'pass127'),
('Leonid', 'leonid128@example.com', 'pass128'),
('Vera', 'vera129@example.com', 'pass129'),
('Fedor', 'fedor130@example.com', 'pass130'),
('Anastasia', 'anastasia131@example.com', 'pass131'),
('Boris', 'boris132@example.com', 'pass132'),
('Galina', 'galina133@example.com', 'pass133'),
('Vitaly', 'vitaly134@example.com', 'pass134'),
('Inna', 'inna135@example.com', 'pass135'),
('Stanislav', 'stanislav136@example.com', 'pass136'),
('Olga', 'olga137@example.com', 'pass137'),
('Yaroslav', 'yaroslav138@example.com', 'pass138'),
('Marina', 'marina139@example.com', 'pass139'),
('Semyon', 'semyon140@example.com', 'pass140'),
('Ekaterina', 'ekaterina141@example.com', 'pass141'),
('Nikita', 'nikita142@example.com', 'pass142'),
('Zoya', 'zoya143@example.com', 'pass143'),
('Oleg', 'oleg144@example.com', 'pass144'),
('Raisa', 'raisa145@example.com', 'pass145'),
('Vasiliy', 'vasiliy146@example.com', 'pass146'),
('Tamara', 'tamara147@example.com', 'pass147'),
('Gleb', 'gleb148@example.com', 'pass148'),
('Sofia', 'sofia149@example.com', 'pass149'),
('Maksim', 'maksim150@example.com', 'pass150'),
('Polina', 'polina151@example.com', 'pass151'),
('Lev', 'lev152@example.com', 'pass152'),
('Viktoria', 'viktoria153@example.com', 'pass153'),
('Ilya', 'ilya154@example.com', 'pass154'),
('Nadezhda', 'nadezhda155@example.com', 'pass155'),
('Anton', 'anton156@example.com', 'pass156'),
('Lyubov', 'lyubov157@example.com', 'pass157'),
('Ruslan', 'ruslan158@example.com', 'pass158'),
('Dina', 'dina159@example.com', 'pass159'),
('Kirill', 'kirill160@example.com', 'pass160'),
('Alevtina', 'alevtina161@example.com', 'pass161'),
('Egor', 'egor162@example.com', 'pass162'),
('Valentina', 'valentina163@example.com', 'pass163'),
('Sasha', 'sasha164@example.com', 'pass164'),
('Miron', 'miron165@example.com', 'pass165'),
('Lidiya', 'lidiya166@example.com', 'pass166'),
('Vsevolod', 'vsevolod167@example.com', 'pass167'),
('Agata', 'agata168@example.com', 'pass168'),
('Matvey', 'matvey169@example.com', 'pass169'),
('Rozalia', 'rozalia170@example.com', 'pass170'),
('Vladislav', 'vladislav171@example.com', 'pass171'),
('Elvira', 'elvira172@example.com', 'pass172'),
('Faina', 'faina173@example.com', 'pass173'),
('Savva', 'savva174@example.com', 'pass174'),
('Varvara', 'varvara175@example.com', 'pass175'),
('Leontiy', 'leontiy176@example.com', 'pass176'),
('Yuliana', 'yuliana177@example.com', 'pass177'),
('Damir', 'damir178@example.com', 'pass178'),
('Larisa', 'larisa179@example.com', 'pass179'),
('Timofey', 'timofey180@example.com', 'pass180'),
('Karolina', 'karolina181@example.com', 'pass181'),
('Evgeny', 'evgeny182@example.com', 'pass182'),
('Sofiya', 'sofiya183@example.com', 'pass183'),
('Nina', 'nina184@example.com', 'pass184'),
('Miron', 'miron185@example.com', 'pass185'),
('Albina', 'albina186@example.com', 'pass186'),
('Grigory', 'grigory187@example.com', 'pass187'),
('Daria', 'daria188@example.com', 'pass188'),
('Ruslan', 'ruslan189@example.com', 'pass189'),
('Vera', 'vera190@example.com', 'pass190'),
('Bogdan', 'bogdan191@example.com', 'pass191'),
('Zinaida', 'zinaida192@example.com', 'pass192'),
('Aleksey', 'aleksey193@example.com', 'pass193'),
('Regina', 'regina194@example.com', 'pass194'),
('Miroslav', 'miroslav195@example.com', 'pass195'),
('Yelena', 'yelena196@example.com', 'pass196'),
('Stanislav', 'stanislav197@example.com', 'pass197'),
('Galina', 'galina198@example.com', 'pass198'),
('Vadim', 'vadim199@example.com', 'pass199'),
('Karina', 'karina200@example.com', 'pass200');

-- changeset ilyatr:2-insert-events
INSERT INTO events (title, date, category, price) VALUES
('Concert of the Year', '2025-12-01 19:00:00', 'Concert', 5000),
('Rock Festival', '2025-12-05 17:00:00', 'Festival', 3500),
('Jazz Evening', '2025-12-08 20:00:00', 'Concert', 2000),
('Electronic Music Party', '2025-12-10 22:00:00', 'Party', 1500),
('Classical Symphony', '2025-12-12 18:00:00', 'Concert', 4000),
('Theater Premiere', '2025-12-15 19:30:00', 'Theater', 2500),
('Modern Art Exhibition', '2025-12-18 10:00:00', 'Exhibition', 1000),
('Cinema Marathon', '2025-12-20 12:00:00', 'Cinema', 800),
('Stand-up Comedy Night', '2025-12-22 21:00:00', 'Comedy', 1800),
('Opera Performance', '2025-12-25 19:00:00', 'Theater', 4500),
('Dance Show', '2025-12-27 18:30:00', 'Dance', 2200),
('Children Theater', '2025-12-28 16:00:00', 'Theater', 1200),
('Photo Exhibition', '2025-12-29 11:00:00', 'Exhibition', 900),
('New Year Party', '2025-12-31 23:00:00', 'Party', 6000),
('Indie Music Festival', '2026-01-03 19:00:00', 'Festival', 2800),
('Piano Recital', '2026-01-05 19:00:00', 'Concert', 3200),
('Magic Show', '2026-01-07 18:00:00', 'Show', 1700),
('Art Fair', '2026-01-09 10:00:00', 'Exhibition', 1300),
('Film Festival', '2026-01-12 14:00:00', 'Cinema', 2000),
('Comedy Central Live', '2026-01-15 20:00:00', 'Comedy', 2500);

-- changeset ilyatr:3-insert-subscriptions
INSERT INTO subscriptions (user_id, event_id) VALUES
(1, 1), (2, 1), (3, 1), (4, 1), (5, 1),
(1, 2), (2, 2), (6, 2), (7, 2), (8, 2),
(3, 3), (4, 3), (5, 3), (9, 3), (10, 3),
(6, 4), (7, 4), (8, 4), (11, 4), (12, 4),
(9, 5), (10, 5), (13, 5), (14, 5), (15, 5),
(1, 6), (2, 6), (3, 6), (16, 6), (17, 6),
(4, 7), (5, 7), (6, 7), (18, 7), (19, 7),
(7, 8), (8, 8), (9, 8), (20, 8), (21, 8),
(10, 9), (11, 9), (12, 9), (22, 9), (23, 9),
(13, 10), (14, 10), (15, 10), (24, 10), (25, 10),
(16, 11), (17, 11), (18, 11), (26, 11), (27, 11),
(19, 12), (20, 12), (21, 12), (28, 12), (29, 12),
(22, 13), (23, 13), (24, 13), (30, 13), (31, 13),
(25, 14), (26, 14), (27, 14), (32, 14), (33, 14),
(28, 15), (29, 15), (30, 15), (34, 15), (35, 15),
(31, 16), (32, 16), (33, 16), (36, 16), (37, 16),
(34, 17), (35, 17), (36, 17), (38, 17), (39, 17),
(37, 18), (38, 18), (39, 18), (40, 18), (41, 18),
(40, 19), (41, 19), (42, 19), (43, 19), (44, 19),
(42, 20), (43, 20), (44, 20), (45, 20), (46, 20);

-- changeset ilyatr:4-insert-comments
INSERT INTO comments (user_id, event_id, text) VALUES
                                                   (1, 1, 'Очень мощный концерт!'),
                                                   (2, 1, 'Вокал просто супер!'),
                                                   (3, 1, 'Классная атмосфера'),
                                                   (4, 1, 'Зал был великолепный'),
                                                   (5, 1, 'Хочу ещё!'),
                                                   (6, 2, 'Отличный фестиваль'),
                                                   (7, 2, 'Рок был шикарный'),
                                                   (8, 2, 'Публика зажигала'),
                                                   (9, 2, 'Супер звук'),
                                                   (10, 2, 'Крутые музыканты'),
                                                   (11, 3, 'Джаз как всегда великолепен'),
                                                   (12, 3, 'Музыка расслабляет'),
                                                   (13, 3, 'Прекрасная подача'),
                                                   (14, 3, 'Классный вечер'),
                                                   (15, 3, 'Очень понравилось'),
                                                   (16, 4, 'Отличный диджей!'),
                                                   (17, 4, 'Зажали как надо'),
                                                   (18, 4, 'Очень драйвово'),
                                                   (19, 4, 'Танцевал до упаду'),
                                                   (20, 4, 'Клуб был идеален'),
                                                   (21, 5, 'Симфония супер'),
                                                   (22, 5, 'Оркестр шикарен'),
                                                   (23, 5, 'Волшебный звук'),
                                                   (24, 5, 'Очень трогательно'),
                                                   (25, 5, 'Потрясающее исполнение'),
                                                   (26, 6, 'Игра актеров великолепна'),
                                                   (27, 6, 'Классный спектакль'),
                                                   (28, 6, 'Интересный сюжет'),
                                                   (29, 6, 'Глубокая постановка'),
                                                   (30, 6, 'Очень понравилось'),
                                                   (31, 7, 'Современное искусство впечатляет'),
                                                   (32, 7, 'Креативные работы'),
                                                   (33, 7, 'Визуально красиво'),
                                                   (34, 7, 'Вдохновляющая выставка'),
                                                   (35, 7, 'Много талантливых авторов'),
                                                   (36, 8, 'Хороший киносет'),
                                                   (37, 8, 'Понравился выбор фильмов'),
                                                   (38, 8, 'Ностальгическая атмосфера'),
                                                   (39, 8, 'Чудесный марафон'),
                                                   (40, 8, 'С удовольствием посмотрел'),
                                                   (41, 9, 'Очень смешной стендап'),
                                                   (42, 9, 'Смеялся весь вечер'),
                                                   (43, 9, 'Умный юмор'),
                                                   (44, 9, 'Комик супер'),
                                                   (45, 9, 'Буду ждать следующий'),
                                                   (46, 10, 'Опера великолепна'),
                                                   (47, 10, 'Красивые голоса'),
                                                   (48, 10, 'Потрясающе исполнено'),
                                                   (49, 10, 'Костюмы шикарные'),
                                                   (50, 10, 'Очень красиво'),
                                                   (1, 11, 'Танцы были энергичные'),
                                                   (2, 11, 'Хореография сильная'),
                                                   (3, 11, 'Очень красиво двигались'),
                                                   (4, 11, 'Слаженная команда'),
                                                   (5, 11, 'Получил удовольствие'),
                                                   (6, 12, 'Забавный спектакль'),
                                                   (7, 12, 'Милое представление'),
                                                   (8, 12, 'Детям понравилось'),
                                                   (9, 12, 'Очень красочно'),
                                                   (10, 12, 'Симпатичное шоу'),
                                                   (11, 13, 'Фото очень красивые'),
                                                   (12, 13, 'Много эстетики'),
                                                   (13, 13, 'Каждый кадр уникален'),
                                                   (14, 13, 'Замечательная выставка'),
                                                   (15, 13, 'Хорошая подача работ'),
                                                   (16, 14, 'Новый год отпраздновали отлично'),
                                                   (17, 14, 'Супервечеринка'),
                                                   (18, 14, 'Зажгли по-полной'),
                                                   (19, 14, 'Отличная компания'),
                                                   (20, 14, 'Весело и шумно'),
                                                   (21, 15, 'Инди музыка супер'),
                                                   (22, 15, 'Талантливые исполнители'),
                                                   (23, 15, 'Уютная атмосфера'),
                                                   (24, 15, 'Много новых имен'),
                                                   (25, 15, 'Очень душевно'),
                                                   (26, 16, 'Фортепиано звучало чудесно'),
                                                   (27, 16, 'Эмоциональная игра'),
                                                   (28, 16, 'Талантливый музыкант'),
                                                   (29, 16, 'Очень трогательно'),
                                                   (30, 16, 'Запомнилось надолго'),
                                                   (31, 17, 'Фокусы были невероятные'),
                                                   (32, 17, 'Как они это делают?!'),
                                                   (33, 17, 'Очень удивило'),
                                                   (34, 17, 'Потрясающее шоу'),
                                                   (35, 17, 'Глаз не оторвать'),
                                                   (36, 18, 'Интересные работы мастеров'),
                                                   (37, 18, 'Купил подарок'),
                                                   (38, 18, 'Красивые изделия'),
                                                   (39, 18, 'Много ручной работы'),
                                                   (40, 18, 'Теплая атмосфера'),
                                                   (41, 19, 'Фильмы разнообразные'),
                                                   (42, 19, 'Интересная программа'),
                                                   (43, 19, 'Хорошая организация'),
                                                   (44, 19, 'Много качественного кино'),
                                                   (45, 19, 'Познавательное мероприятие'),
                                                   (46, 20, 'Комики супер!'),
                                                   (47, 20, 'Очень смешное шоу'),
                                                   (48, 20, 'Насмеялся вдоволь'),
                                                   (49, 20, 'Юмор на уровне'),
                                                   (50, 20, 'Замечательное выступление'),
                                                   (51, 1, 'Очень понравилось выступление'),
                                                   (52, 2, 'Хорошие музыканты'),
                                                   (53, 3, 'Джаз был на высоте'),
                                                   (54, 4, 'Электронная музыка просто бомба'),
                                                   (55, 5, 'Оркестр играл шикарно'),
                                                   (56, 6, 'Спектакль очень глубокий'),
                                                   (57, 7, 'Много интересных работ'),
                                                   (58, 8, 'Классный выбор фильмов'),
                                                   (59, 9, 'Комик поднял настроение'),
                                                   (60, 10, 'Очень красивая постановка'),
                                                   (61, 11, 'Танцоры большие молодцы'),
                                                   (62, 12, 'Шоу было милым'),
                                                   (63, 13, 'Фото как живые'),
                                                   (64, 14, 'Вечеринка была весёлой'),
                                                   (65, 15, 'Приятная атмосфера'),
                                                   (66, 16, 'Пианист виртуоз'),
                                                   (67, 17, 'Волшебство на сцене'),
                                                   (68, 18, 'Купил сувенир'),
                                                   (69, 19, 'Фильмы были интересные'),
                                                   (70, 20, 'Шоу очень забавное'),
                                                   (71, 1, 'Прекрасный концерт'),
                                                   (72, 2, 'Потрясающая энергетика'),
                                                   (73, 3, 'Джаз прекрасен'),
                                                   (74, 4, 'Ритмы впечатляют'),
                                                   (75, 5, 'Очень эмоционально'),
                                                   (76, 6, 'Актеры играли замечательно'),
                                                   (77, 7, 'Вдохновляющее искусство'),
                                                   (78, 8, 'Кино заставило задуматься'),
                                                   (79, 9, 'Море смеха'),
                                                   (80, 10, 'Красивые голоса'),
                                                   (81, 11, 'Потрясающая пластика'),
                                                   (82, 12, 'Хороший спектакль'),
                                                   (83, 13, 'Великолепные фотографии'),
                                                   (84, 14, 'Настоящий праздник'),
                                                   (85, 15, 'Открыл для себя новые группы'),
                                                   (86, 16, 'Музыка была душевной'),
                                                   (87, 17, 'Фокусы удивляли'),
                                                   (88, 18, 'Много талантливых мастеров'),
                                                   (89, 19, 'Интересные фильмы'),
                                                   (90, 20, 'Юмор тонкий'),
                                                   (91, 1, 'Классный звук'),
                                                   (92, 2, 'Прям мурашки'),
                                                   (93, 3, 'Джаз — любовь'),
                                                   (94, 4, 'Зажигательно'),
                                                   (95, 5, 'Шикарно играли'),
                                                   (96, 6, 'Прекрасная постановка'),
                                                   (97, 7, 'Очень красиво'),
                                                   (98, 8, 'Неплохие фильмы'),
                                                   (99, 9, 'Очень весело'),
                                                   (100, 10, 'Опера прекрасна'),
                                                   (101, 11, 'Хореография удивительная'),
                                                   (102, 12, 'С детьми было весело'),
                                                   (103, 13, 'Работы впечатляют'),
                                                   (1, 14, 'Новый год был шикарным'),
                                                   (2, 15, 'Музыка зажигала'),
                                                   (3, 16, 'Глубокая музыка'),
                                                   (4, 17, 'Удивительное шоу'),
                                                   (5, 18, 'Приятно провел время'),
                                                   (6, 19, 'Фильмы были разными'),
                                                   (7, 20, 'Отличный комик');